language: go
go:
  - "stable"

cache:
  directories:
    - $GOPATH/pkg/mod

stages:
  - Test
  - Release
  - OBS Commit
  - OBS Submit Request

jobs:
  include:
    - stage: Test
      name: Static checks
      script: make static-checks
    - stage: Test
      name: Unit tests
      script: make test
    - stage: Release
      name: Build and upload binaries on GitHub
      if: tag IS present
      services:
        - docker
      env:
        - VERSION=$TRAVIS_TAG
      script:
        - make -j4 build-all
      deploy:
        provider: releases
        token: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: build/bin/*
        name: $TRAVIS_TAG
        # ignore Travis alias warning, using "cleanup" doesn't work
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
    - stage: OBS commit
      name: Commit to OBS dev project
      if: branch = master OR tag IS present
      services:
        - docker
      env:
        - VERSION=$TRAVIS_BRANCH
      script:
        - |
          docker run --rm -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e OBS_PACKAGE -e VERSION -e REPOSITORY=$TRAVIS_REPO_SLUG -e GITHUB_OAUTH_TOKEN \
          shap/continuous_deliver \
          bash -c "/scripts/init_osc_creds.sh && make obs-commit"
    - stage: OBS Submit Request
      name: Submit Request to OBS stable project
      if: tag IS present
      services:
        - docker
      env:
        - VERSION=$TRAVIS_TAG
      script:
        - |
          docker run --rm -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e PACKAGE_NAME=$OBS_PACKAGE -e TARGET_PROJECT=$OBS_DOWNSTREAM_PROJECT \
          shap/continuous_deliver \
          bash -c "/scripts/submit.sh"
