language: go
go:
  - "stable"

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: Test
      name: Static checks
      script: make static-checks
    - stage: Test
      name: Unit tests
      script: make test
    - stage: Build & release
      if: tag IS present
      services:
        - docker
      env:
        - VERSION=$TRAVIS_TAG
      script:
        - make -j4 build-all
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: yes
        file: build/bin/*
        name: $TRAVIS_TAG
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - |
          docker run --rm -t -v "$(pwd):/package" -v "$GOPATH/pkg/mod:/root/go/pkg/mod" -w /package \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e OBS_PACKAGE -e VERSION -e REPOSITORY=$TRAVIS_REPO_SLUG \
          shap/continuous_deliver \
          bash -c "/scripts/init_osc_creds.sh && make obs-commit" || travis_terminate 1
